name: .NET 7.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Test
      env: 
        REPORT_RESULTS_API_ENDPOINT: ${{ secrets.REPORT_RESULTS_API_ENDPOINT }}
        REPORT_RESULTS_API_KEY: ${{ secrets.REPORT_RESULTS_API_KEY }}
      run: dotnet run --project ./dotnet
